### ISSUE TITLE
Create model for spinal cord centerline detection

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/canproco#7]
Our current approach for MS lesion detection/segmentation is to (i) segment the spina cord, (ii) crop it using the segmentation mask and (iii) use the cropped output for training a model.

However, this is sub-efficient, considering that the spinal cord segmentation itself relies on spinal cord centerline detection. 

Idea: Train a _robust_ model for centerline detection, which outputs would be used in lieu of the spinal cord segmentation, for training DL models.

**Comment by sandrinebedard** [comment]
## UPDATE (after meeting 2022-11-24)

We discussed the pros and cons of training a model to detect the centerline.

**PROS:**

- We would not need to correct the segmentations errors
- More efficient since the spinal cord segmentation is used to get the centerline, we could directly use the centerline for the training of our  DL models

**CONS:**

- segmentation is useful to co-register contrast together
- only 5-10% (for T2w) needed manual correction
- To first generate the centerline, we need the segmentation
- the spinal cord segmentation can be used to validate if a lesion is detected in the cord for example 

**VERDICT:** we willl continue with the spinal cord segmentation (corrected) to get the centerline

**Comment by naga-karthik** [comment]
Closing this as progress is being followed on another issue mentioned above!
